export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	BotService: Symbol.for('BotService'),
	PrismaController: Symbol.for('PrismaController'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	ServerService: Symbol.for('ServerService'),
	ExeptionFilter: Symbol.for('ExeptionFilter'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	UsersRepository: Symbol.for('UsersRepository'),
	CityController: Symbol.for('CityController'),
	CityService: Symbol.for('CityService'),
	CityRepository: Symbol.for('CityRepository'),
	PromotionController: Symbol.for('PromotionController'),
	PromotionService: Symbol.for('PromotionService'),
	PromotionRepository: Symbol.for('PromotionRepository'),
	TopicController: Symbol.for('TopicController'),
	TopicService: Symbol.for('TopicService'),
	TopicRepository: Symbol.for('TopicRepository'),
};
